# SwiftLint configuration file for iOS project

# Rule inclusions and exclusions
included:
  - Memolink

excluded:
  - Pods
  - .build
  - DerivedData
  - Carthage/Checkouts
  - fastlane
  - .bundle
  - MemolinkTests
  - "**/*Tests.swift"
  - "**/*Test.swift"

# Enabled rules (in addition to default rules)
opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  - implicitly_unwrapped_optional
  - overridden_super_call
  - redundant_nil_coalescing
  - switch_case_on_newline
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

# Disabled rules
disabled_rules:
  - trailing_whitespace
  - todo
  - multiple_closures_with_trailing_closure
  - large_tuple

# Rule configurations
line_length:
  warning: 100
  error: 120
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true
  ignores_interpolated_strings: true

file_length:
  warning: 400
  error: 500

function_body_length:
  warning: 60
  error: 100

type_body_length:
  warning: 300
  error: 400

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - url
    - x
    - y
    - z
    - i
    - j

cyclomatic_complexity:
  warning: 8
  error: 15

nesting:
  type_level: 3
  function_level: 6

type_name:
  min_length: 3
  max_length: 40

# SwiftUI specific configurations
function_parameter_count:
  warning: 7
  error: 10

# Trailing comma rule (useful for SwiftUI)
trailing_comma:
  mandatory_comma: false

# Custom rules
custom_rules:
  no_objcMembers:
    name: "@objcMembers"
    message: "@objcMembers is not recommended"
    regex: "@objcMembers"
    severity: warning

# Reporter type
reporter: "xcode"
